web/web/urls.py
from django.contrib import admin
from django.conf.urls import include, url
from .views import index
from hcmfront import views

urlpatterns = [
    #url(r'^', index),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^$', views.index, name='index'),
    url(r'^update/meetingroomlist$', views.update_meeting_room_list, name='update_meeting_room_list'),
    url(r'^reservation/new/$', views.reservation_new, name='reservation_new'),
    url(r'^request/new/$', views.request_new, name='request_new'),
]

web/hcmfront/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.core.exceptions import ValidationError
from django.db import models
from django.core.urlresolvers import reverse

# Create your models here.
class Availability(models.Model):
    start_time = models.TimeField(u'Hora  de Inicio', help_text=u'Horario de Disponibilidad')
    end_time = models.TimeField(u'Hora de Fin', help_text=u'Horario de Disponibilidad')

    def __str__(self):
        return u'%s : %s' % (self.start_time, self.end_time)

    class Meta:
        verbose_name = u'Horario de Disponibilidad'
        verbose_name_plural = u'Horarios Disponibles'

class Input(models.Model):
    name = models.CharField(u'Nombre', help_text=u'Nombre del Insumo', max_length=250)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = u'Insumo'
        verbose_name_plural = u'Insumos'


class MeetingRoom(models.Model):
    name = models.CharField(u'Nombre', help_text=u'Nombre de la Sala', max_length=250)
    location = models.CharField(u'Ubicacion', help_text=u'Ubicacion de la Sala', blank=True, null=True, max_length=500)
    capacity = models.IntegerField(u'Capacidad', help_text=u'Capacidad de la Sala')

    availability = models.ManyToManyField(Availability, verbose_name=u'Horarios Disponibles', help_text=u'Lista de horarios disponibles.')
    supplies = models.ManyToManyField(Input, verbose_name=u'Insumos', help_text=u'Lista de insumos disponibles.')

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = u'Sala de Reuniones'
        verbose_name_plural = u'Salas de Reuniones'


class Employee(models.Model):
    name = models.CharField(u'Nombre', help_text=u'Nombre del Empleado', max_length=250)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = u'Empleados'
        verbose_name_plural = u'Empleados'


class ReservationMeetingRoom(models.Model):
    date = models.DateField(u'Fecha', help_text=u'Fecha de inicio de la Reservacion')
    start_time = models.TimeField(u'Hora  de Inicio', help_text=u'Horario de la Reservacion')
    end_time = models.TimeField(u'Hora de Fin', help_text=u'Horario de la Reservacion')
    amount_people = models.IntegerField(u'Cantidad de Personas', help_text=u'Cantidad de Personas de la Reservacion')

    meeting_room = models.ForeignKey(MeetingRoom, on_delete=models.CASCADE, verbose_name=u'Sala de Reuniones', help_text=u'Sala de Reunion reservada.')
    employee = models.ForeignKey(Employee, on_delete=models.CASCADE, verbose_name=u'Empleado', help_text=u'Empleado que realiza la reservacion.')
    supplies = models.ManyToManyField(Input, verbose_name=u'Lista de insumos', help_text=u'Insumos seleccionados para la reservacion.')

    def __str__(self):
        return u'Sala: %s Empleado: %s Horario: %s %s:%s' % (self.meeting_room.name, self.employee.name, self.date, self.start_time, self.end_time)

    class Meta:
        verbose_name = u'Reservacion'
        verbose_name_plural = u'Reservaciones'

    def check_overlap(self, fixed_start, fixed_end, new_start, new_end):
        overlap = False
        if new_start == fixed_end or new_end == fixed_start:  # edge case
            overlap = False
        elif (new_start >= fixed_start and new_start <= fixed_end) or (
                new_end >= fixed_start and new_end <= fixed_end):  # innner limits
            overlap = True
        elif new_start <= fixed_start and new_end >= fixed_end:  # outter limits
            overlap = True

        return overlap

    def get_absolute_url(self):
        url = reverse('admin:%s_%s_change' % (self._meta.app_label, self._meta.model_name), args=[self.id])
        return u'<a href="%s">%s</a>' % (url, str(self.start_time))

    def clean(self):
        if self.end_time <= self.start_time:
            raise ValidationError('La hora final debe ser mayor que la hora inicial.')

        reservations = ReservationMeetingRoom.objects.filter(date=self.date)
        if reservations.exists():
            for reservation in reservations:
                if self.check_overlap(reservation.start_time, reservation.end_time, self.start_time, self.end_time):
                    raise ValidationError(
                        'Esta reservacion se sobrepone con otra: ' + str(reservation.date) + ', ' + str(
                            reservation.start_time) + '-' + str(reservation.end_time))


class RequestMeetingRoom(models.Model):
    status = models.NullBooleanField(u'Estado', help_text=u'Especifica si la peticion fue aceptada', blank=True, null=True)

    reservation_meeting_room = models.ForeignKey(ReservationMeetingRoom, on_delete=models.CASCADE, verbose_name=u'Reservacion', help_text=u'Reservacion de Sala de Reservacion a la cual se realiza la peticion.')
    employee = models.ForeignKey(Employee, on_delete=models.CASCADE, verbose_name=u'Empleado', help_text=u'Empleado que realiza la peticion.')

    def __str__(self):
        return u'%s %s:%s' % (self.employee.name, self.reservation_meeting_room, self.status)

    class Meta:
        verbose_name = u'Solicitar Sala de Reuniones'
        verbose_name_plural = u'Solicitudes de Salas de Reuniones'

web/hcmfront/forms.py
from django import forms
from django.contrib.admin import widgets

from .models import ReservationMeetingRoom,RequestMeetingRoom

class ReservationMeetingRoomForm(forms.ModelForm):

    class Meta:
        model = ReservationMeetingRoom
        fields = ('date', 'start_time', 'end_time', 'amount_people', 'employee', 'supplies', 'meeting_room')
        widgets = {
             'date': forms.DateInput(attrs={'class': 'datepicker'}),
             'start_time': forms.TimeInput(attrs={'class': 'timepicker'}),
             'end_time': forms.TimeInput(attrs={'class': 'timepicker'}),

        }

class RequestMeetingRoomForm(forms.ModelForm):

    class Meta:
        model = RequestMeetingRoom
        fields = ('reservation_meeting_room', 'employee')

web/hcmfront/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.http import HttpResponse, JsonResponse
from hcmfront.forms import ReservationMeetingRoomForm,RequestMeetingRoomForm
from hcmfront.models import ReservationMeetingRoom, MeetingRoom

from django.shortcuts import render
from django.shortcuts import redirect
from django.core import serializers
# Create your views here.


def reservation_new(request):
    if request.method == "POST":
        form = ReservationMeetingRoomForm(request.POST)
        if form.is_valid():
            reservation = form.save(commit=False)
            reservation.save()
            return redirect('index')
    else:
        form = ReservationMeetingRoomForm()
    return render(request, 'reservation.html', {'form': form})

def request_new(request):
    if request.method == "POST":
        form = RequestMeetingRoomForm(request.POST)
        if form.is_valid():
            requestRoom = form.save(commit=False)
            requestRoom.save()
            return redirect('index')
    else:
        form = RequestMeetingRoomForm()
    return render(request, 'request.html', {'form': form})


def index(request):
    return render(request, 'index.html')

def update_meeting_room_list(request):
    if request.method == "POST" and request.is_ajax():

        date = request.POST['date']
        start_time = request.POST['start_time']
        end_time = request.POST['end_time']
        amount_people = request.POST['amount_people']
        supplies = request.POST['supplies[]']

        meeting_room = MeetingRoom.objects.filter(capacity__gte=amount_people, supplies__id=supplies).values_list('id', 'name')

        return JsonResponse({'results': list(meeting_room)})
    else:
        status= "Bad"
        return HttpResponse(status)

web/hcmfront/templates/base.html
{% load staticfiles %}
<html>
    <head>
        <title>HCMFront Test</title>
        <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/timepicker/1.3.5/jquery.timepicker.min.css">
        <link href="https://code.jquery.com/ui/1.12.1/themes/smoothness/jquery-ui.css" rel="stylesheet" type="text/css">
        <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
        <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
        <link href='//fonts.googleapis.com/css?family=Lobster&subset=latin,latin-ext' rel='stylesheet' type='text/css'>
        {% block css %}
        {% endblock %}
    </head>
    <body>
        <div class="page-header">
            <h1><a href="/">HCMFront Test</a></h1>
        </div>
        <div class="content container">
            <div class="row">
                <div class="col-md-8">
                    {% block content %}
                    {% endblock %}
                </div>
            </div>
        </div>
    </body>
    <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/timepicker/1.3.5/jquery.timepicker.min.js"></script>
    {% block scripts %}
    {% endblock %}

</html>

web/hcmfront/templates/index.html
{% extends 'base.html' %}

{% block content %}
        <a href="{% url 'reservation_new' %}" class="top-menu">Agregar una solicitud<span class="glyphicon glyphicon-plus"></span></a>
        <a href="{% url 'request_new' %}" class="top-menu">Agregar una peticion<span class="glyphicon glyphicon-plus"></span></a>
        <a href="{% url 'admin:index' %}" class="top-menu">Admin Site<span class="glyphicon glyphicon-plus"></span></a>

{% endblock %}

web/hcmfront/templates/post_edit.html
{% extends 'base.html' %}

{% block content %}
    <h1>New post</h1>
    <form method="POST" class="post-form">{% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="save btn btn-default">Save</button>
    </form>
{% endblock %}

web/hcmfront/templates/request.html
{% extends 'base.html' %}

{% block content %}
    <h1>Nueva Peticion</h1>
    <form method="POST" class="post-form">{% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="save btn btn-default">Save</button>
    </form>
{% endblock %}

web/hcmfront/templates/reservation.html
{% extends 'base.html' %}

{% block content %}
    <h1>Nueva Reservacion</h1>
    <form method="POST" class="post-form">{% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="save btn btn-default">Save</button>
    </form>
{% endblock %}

{% block scripts %}

    <script>
      $(function() {
           $('#id_meeting_room')
            .find('option')
            .remove()
            .end()
            .append('<option value="whatever">Seleccione Cantidad de personas e Insumos</option>')
            .val('whatever')
        ;
        $( ".datepicker" ).datepicker({
          changeMonth: true,
          changeYear: true,
          yearRange: "1900:2012",
          // You can put more options here.

        });
        $('.timepicker').timepicker({ timeFormat: 'h:mm' });
        //id_meeting_room
          function updateMeetingRoomList() {
              console.log($("#id_supplies").val());
            $.ajax({
                url: "{% url 'update_meeting_room_list' %}",
                type: "post", //send it through get method
                data: {
                    date: $("#id_date").val(),
                    start_time: $("#id_start_time").val(),
                    end_time: $("#id_end_time").val(),
                    amount_people: $("#id_amount_people").val(),
                    supplies: $("#id_supplies").val(),

                },
                success: function(response) {
                    console.log(response)
                     $('#id_meeting_room')
                        .find('option')
                        .remove()
                        .end()
        ;
                    //Do Something
                    var $dropdown = $("#id_meeting_room");
                    $.each(response.results, function() {
                                            console.log(this)

                        $dropdown.append($("<option />").val(this[0]).text(this[1]));
                    });
                },
                error: function(xhr) {
                //Do Something to handle error
                }
            });
          };
          $("#id_supplies").on("change", function(event) {
                 updateMeetingRoomList(this);
            } );
      });
      </script>
{% endblock %}